import type { BetaMission } from './types'

export const betaMissions: BetaMission[] = [
  {
    app_area: 'Aba Mais',
    section: 'Podcasts devocionais',
    mission_key: 'podcasts_salmo23_audio_basico',
    area: 'Aba Mais',
    title: 'Testar o áudio de um episódio do Salmo 23',
    estimated_minutes: 7,
    objective:
      'Verificar se o episódio abre corretamente, se o áudio toca no seu aparelho, se os controles do player funcionam e se a legenda sincronizada aparece sem travar a tela.',
    prerequisites: [
      'Faça o teste no aparelho que você realmente usa para acessar o app.',
      'Se possível, deixe o volume do celular audível.',
      'Se estiver no iPhone, teste do jeito que você normalmente abre o app: Safari ou app instalado na tela inicial.',
    ],
    step_by_step: [
      'Entre na aba Mais.',
      'Toque em Podcasts devocionais.',
      'Abra a série Salmo 23.',
      'Na tela da série, procure a seção Episódios.',
      'Toque em qualquer episódio liberado da série.',
      'Confira se abriu a tela do episódio com capa, título, referência bíblica e descrição.',
      'Toque em Voltar aos episódios.',
      'Abra novamente o mesmo episódio.',
      'Toque no botão azul de play.',
      'Aguarde o áudio começar e observe se o tempo atual começa a andar.',
      'Toque novamente no botão para pausar.',
      'Toque outra vez para continuar.',
      'Use o botão +15s para avançar.',
      'Use o botão -15s para voltar.',
      'Arraste a barra de progresso para outro ponto do áudio.',
      'Se aparecer Legenda sincronizada, toque em Ocultar e depois em Mostrar.',
      'Volte para a lista de episódios e confira se o app não travou.',
    ],
    what_to_observe: [
      'O episódio abriu sem tela branca ou travamento?',
      'O áudio começou depois de tocar no play?',
      'O botão mudou de play para pausa?',
      'O tempo atual e o tempo total apareceram corretamente?',
      'A barra de progresso respondeu ao toque?',
      'Os botões +15s e -15s funcionaram?',
      'A legenda sincronizada apareceu, ocultou e mostrou novamente?',
      'No seu aparelho, especialmente iPhone/Safari, o som saiu normalmente?',
      'Ao voltar para os episódios, o app continuou estável?',
    ],
    success_criteria:
      'Consegui abrir o episódio, tocar, pausar, avançar, voltar e usar a legenda sem problema.',
    problem_criteria:
      'O áudio não tocou, travou, ficou sem som, a tela quebrou ou algum controle não funcionou.',
    confusing_criteria:
      'Não soube onde clicar, não encontrei a série, não entendi o player ou fiquei confuso em algum passo.',
    criticality: 'alta',
    type: 'áudio',
  },
  {
    app_area: 'Aba Hoje',
    section: 'Áudio de Hoje',
    mission_key: 'hoje_ouvir_audio_do_dia',
    area: 'Aba Hoje',
    title: 'Ouvir o Áudio de Hoje',
    estimated_minutes: 5,
    objective:
      'Confirmar se o Áudio de Hoje começa a tocar, se o Mini Player aparece e se é possível pausar, retomar, expandir e fechar o player.',
    prerequisites: ['Ter um devocional publicado na Aba Hoje com áudio disponível.'],
    step_by_step: [
      'Abra o app na Aba Hoje.',
      'Procure o card Áudio de hoje.',
      'Toque na imagem grande ou no título dentro do card.',
      'Observe se o áudio começa a tocar.',
      'Veja se aparece um Mini Player na parte de baixo da tela.',
      'No Mini Player, toque no botão de pausar.',
      'Depois toque novamente para continuar.',
      'Toque no botão de expandir o player.',
      'Observe se abre a tela grande do player.',
      'Feche ou minimize o player e volte para a Aba Hoje.',
      'Toque no botão de fechar do Mini Player.',
    ],
    what_to_observe: [
      'Se o áudio inicia sem travar.',
      'Se o tempo do áudio anda.',
      'Se pausar e retomar funcionam.',
      'Se o player expandido abre corretamente.',
      'Se o fechamento realmente para ou oculta o player.',
    ],
    success_criteria:
      'O áudio tocou, pausou, voltou a tocar, abriu o player expandido e fechou sem erro.',
    problem_criteria:
      'O áudio não toca, o player não aparece, o botão de pausa não funciona, o tempo fica parado ou o app trava.',
    confusing_criteria:
      'O testador não soube onde tocar para iniciar ou pausar o áudio.',
    criticality: 'alta',
    type: 'áudio',
  },
  {
    app_area: 'Aba Hoje',
    section: 'Áudio de Hoje',
    mission_key: 'hoje_audio_iphone_safari_pwa',
    area: 'Aba Hoje',
    title: 'Testar Áudio no iPhone/Safari',
    estimated_minutes: 8,
    objective:
      'Confirmar se o Áudio de Hoje funciona bem em iPhone, Safari ou app instalado como PWA.',
    prerequisites: [
      'Missão apenas para quem usa iPhone, Safari ou app instalado como PWA.',
      'Ter um devocional publicado com áudio disponível.',
    ],
    step_by_step: [
      'Abra o app pelo Safari no iPhone ou pelo ícone instalado na tela inicial.',
      'Entre na Aba Hoje.',
      'Toque no card Áudio de hoje.',
      'Aguarde alguns segundos.',
      'Observe se o áudio começa sem erro.',
      'Bloqueie a tela por alguns segundos, se se sentir confortável.',
      'Volte ao app.',
      'Pause e retome pelo Mini Player.',
      'Abra o player expandido.',
      'Observe se título, tempo e controles aparecem corretamente.',
    ],
    what_to_observe: [
      'Se o áudio carrega no iPhone.',
      'Se o áudio continua estável.',
      'Se os botões respondem.',
      'Se o player não some de forma estranha.',
    ],
    success_criteria:
      'O áudio tocou normalmente no iPhone/Safari/PWA e os controles funcionaram.',
    problem_criteria:
      'O áudio não inicia, fica carregando, para sozinho ou não retoma.',
    confusing_criteria:
      'O testador não soube dizer se estava usando Safari, iPhone ou PWA.',
    criticality: 'alta',
    type: 'áudio',
  },
  {
    app_area: 'Aba Hoje',
    section: 'Compartilhamento',
    mission_key: 'hoje_compartilhar_palavra_e_audio',
    area: 'Aba Hoje',
    title: 'Compartilhar Palavra e Áudio',
    estimated_minutes: 6,
    objective:
      'Testar se é possível compartilhar a Palavra do Dia e o Áudio de Hoje.',
    prerequisites: [
      'Ter Palavra do Dia publicada.',
      'Ter Áudio de Hoje disponível.',
    ],
    step_by_step: [
      'Abra a Aba Hoje.',
      'No card da Palavra do Dia, toque no botão de compartilhar.',
      'Observe se abre a tela de compartilhamento do celular ou mensagem de link copiado.',
      'Se abrir a tela de compartilhamento, escolha copiar link ou enviar para alguém de confiança.',
      'Volte para a Aba Hoje.',
      'No card Áudio de hoje, toque em Compartilhar.',
      'Observe se abre a tela de compartilhamento ou se o link foi copiado.',
      'Relate se os dois links parecem levar para conteúdos diferentes: Palavra do Dia e áudio.',
    ],
    what_to_observe: [
      'Se os botões respondem.',
      'Se o compartilhamento abre.',
      'Se o app não trava.',
      'Se os links parecem corretos.',
    ],
    success_criteria: 'Conseguiu compartilhar ou copiar os dois links.',
    problem_criteria:
      'Botão não responde, app fecha, link não copia ou compartilhamento abre errado.',
    confusing_criteria:
      'O testador não identificou qual botão compartilha Palavra e qual compartilha áudio.',
    criticality: 'alta',
    type: 'compartilhamento',
  },
  {
    app_area: 'Aba Hoje',
    section: 'Áudio de Hoje',
    mission_key: 'hoje_favoritar_audio_do_dia',
    area: 'Aba Hoje',
    title: 'Favoritar Áudio de Hoje',
    estimated_minutes: 4,
    objective:
      'Verificar se o botão Favorito salva e remove o Áudio de Hoje corretamente.',
    prerequisites: ['Estar cadastrado/logado; sem login, relatar o aviso.'],
    step_by_step: [
      'Abra a Aba Hoje.',
      'Procure o card Áudio de hoje.',
      'Toque no botão Favorito.',
      'Observe se muda para Salvo ou coração preenchido.',
      'Saia da Aba Hoje e volte.',
      'Confira se continua salvo.',
      'Toque novamente em Salvo.',
      'Observe se volta para Favorito.',
    ],
    what_to_observe: [
      'Mudança visual do botão.',
      'Persistência ao sair e voltar.',
      'Mensagem quando não há cadastro/login.',
    ],
    success_criteria: 'Alternou entre Favorito e Salvo corretamente.',
    problem_criteria:
      'Erro, não salva, não remove ou perde estado ao voltar.',
    confusing_criteria: 'O testador não soube se ficou salvo ou não.',
    criticality: 'média',
    type: 'usabilidade',
  },
  {
    app_area: 'Aba Hoje',
    section: 'Notificações',
    mission_key: 'hoje_ativar_lembrete_diario',
    area: 'Aba Hoje',
    title: 'Ativar Lembrete Diário',
    estimated_minutes: 6,
    objective:
      'Testar o botão Lembrete do Áudio de Hoje para ativar ou desativar notificações.',
    prerequisites: [
      'Estar cadastrado/logado.',
      'Pode não funcionar em todos os navegadores.',
    ],
    step_by_step: [
      'Abra a Aba Hoje.',
      'No card Áudio de hoje, toque em Lembrete.',
      'Se o navegador pedir permissão, escolha permitir para testar.',
      'Observe se aparece mensagem de notificações ativadas.',
      'Veja se o ícone muda para sino ativado.',
      'Toque novamente em Lembrete.',
      'Observe se aparece mensagem de notificações desativadas.',
      'Se aparecer aviso de login, navegador sem suporte ou permissão negada, relatar exatamente a mensagem.',
    ],
    what_to_observe: [
      'Pedido de permissão.',
      'Mensagem de sucesso ou erro.',
      'Mudança visual do botão.',
      'Clareza das mensagens.',
    ],
    success_criteria: 'Ativou e desativou com mensagens claras.',
    problem_criteria:
      'Botão trava, não mostra resposta, erro estranho ou pede permissão repetidamente.',
    confusing_criteria:
      'O testador não soube se ficou ligado ou desligado.',
    criticality: 'alta',
    type: 'notificação',
  },
  {
    app_area: 'Aba Hoje',
    section: 'Atalhos',
    mission_key: 'hoje_estado_sem_devocional',
    area: 'Aba Hoje',
    title: 'Aba Hoje Sem Devocional',
    estimated_minutes: 4,
    objective:
      'Avaliar a experiência quando ainda não existe devocional publicado na Aba Hoje.',
    prerequisites: [
      'Só pode ser feita em ambiente onde a Aba Hoje esteja sem devocional publicado.',
    ],
    step_by_step: [
      'Abra o app na Aba Hoje.',
      'Observe se aparece Nenhum devocional publicado.',
      'Leia o texto abaixo.',
      'Toque em Leitura de hoje.',
      'Volte para Aba Hoje.',
      'Toque em Oração de hoje.',
      'Volte para Aba Hoje.',
      'Toque no banner de contribuição/oferta.',
      'Relate se a tela vazia parece acolhedora ou parece erro.',
    ],
    what_to_observe: [
      'Clareza da mensagem.',
      'Ausência de tela quebrada.',
      'Funcionamento dos atalhos.',
      'Tom pastoral do texto.',
    ],
    success_criteria: 'Tela vazia apareceu bem e atalhos funcionaram.',
    problem_criteria:
      'Tela branca, travou, erro técnico ou atalho não abriu.',
    confusing_criteria:
      'O testador achou que o app estava com defeito mesmo sem erro.',
    criticality: 'média',
    type: 'conteúdo',
  },
  {
    app_area: 'Aba Hoje',
    section: 'Atalhos',
    mission_key: 'hoje_navegar_atalhos',
    area: 'Aba Hoje',
    title: 'Navegar Pelos Atalhos da Aba Hoje',
    estimated_minutes: 5,
    objective:
      'Testar os caminhos da Aba Hoje para Série/Podcasts, Leitura, Oração e Oferta.',
    prerequisites: [
      'Ter devocional publicado.',
      'Para Série/Podcasts, episódio precisa mostrar nome da série.',
    ],
    step_by_step: [
      'Abra a Aba Hoje.',
      'No card Áudio de hoje, toque no nome da série, se aparecer no canto superior direito.',
      'Observe se abre a área de séries/podcasts.',
      'Volte para Aba Hoje pelo menu inferior.',
      'Toque em Leitura de hoje.',
      'Volte para Aba Hoje.',
      'Toque em Oração de hoje.',
      'Volte para Aba Hoje.',
      'Toque no banner Contribuição ministerial.',
      'Observe se abre oferta/contribuição.',
    ],
    what_to_observe: [
      'Se cada toque leva para a área esperada.',
      'Se é fácil voltar.',
      'Se algum botão parece pequeno ou difícil de perceber.',
    ],
    success_criteria:
      'Todos os atalhos disponíveis abriram a área correta.',
    problem_criteria:
      'Atalho não responde, abre tela errada ou dificulta voltar.',
    confusing_criteria:
      'O testador não percebeu que cards eram clicáveis ou não entendeu para onde foi levado.',
    criticality: 'média',
    type: 'navegação',
  },
]
